// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/track/:requestId": {
    params: {
      "requestId": string;
    };
  };
  "/webhooks/returns": {
    params: {};
  };
  "/webhooks/returns/request": {
    params: {};
  };
  "/photo/:photoId": {
    params: {
      "photoId": string;
    };
  };
  "/auth/login": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/portal": {
    params: {};
  };
  "/portal/request": {
    params: {};
  };
  "/track": {
    params: {};
  };
  "/app": {
    params: {};
  };
  "/app/notifications": {
    params: {};
  };
  "/app/settings": {
    params: {};
  };
  "/app/returns": {
    params: {};
  };
  "/app/returns/:id": {
    params: {
      "id": string;
    };
  };
  "/app/rules": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/webhooks/app/scopes_update" | "/webhooks/app/uninstalled" | "/track/:requestId" | "/webhooks/returns" | "/webhooks/returns/request" | "/photo/:photoId" | "/auth/login" | "/auth/*" | "/portal" | "/portal/request" | "/track" | "/app" | "/app/notifications" | "/app/settings" | "/app/returns" | "/app/returns/:id" | "/app/rules";
  };
  "routes/webhooks.app.scopes_update.tsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.app.uninstalled.tsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/track.$requestId.tsx": {
    id: "routes/track.$requestId";
    page: "/track/:requestId";
  };
  "routes/webhooks.returns.tsx": {
    id: "routes/webhooks.returns";
    page: "/webhooks/returns" | "/webhooks/returns/request";
  };
  "routes/webhooks.returns.request.tsx": {
    id: "routes/webhooks.returns.request";
    page: "/webhooks/returns/request";
  };
  "routes/photo.$photoId.tsx": {
    id: "routes/photo.$photoId";
    page: "/photo/:photoId";
  };
  "routes/auth.login/route.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/_index/route.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.$.tsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/portal.tsx": {
    id: "routes/portal";
    page: "/portal" | "/portal/request";
  };
  "routes/portal.request.tsx": {
    id: "routes/portal.request";
    page: "/portal/request";
  };
  "routes/portal._index.tsx": {
    id: "routes/portal._index";
    page: "/portal";
  };
  "routes/track..tsx": {
    id: "routes/track.";
    page: "/track";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app" | "/app/notifications" | "/app/settings" | "/app/returns" | "/app/returns/:id" | "/app/rules";
  };
  "routes/app.notifications.tsx": {
    id: "routes/app.notifications";
    page: "/app/notifications";
  };
  "routes/app.settings.tsx": {
    id: "routes/app.settings";
    page: "/app/settings";
  };
  "routes/app.returns.tsx": {
    id: "routes/app.returns";
    page: "/app/returns" | "/app/returns/:id";
  };
  "routes/app.returns.$id.tsx": {
    id: "routes/app.returns.$id";
    page: "/app/returns/:id";
  };
  "routes/app._index.tsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.rules.tsx": {
    id: "routes/app.rules";
    page: "/app/rules";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.tsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.tsx");
  "routes/track.$requestId": typeof import("./app/routes/track.$requestId.tsx");
  "routes/webhooks.returns": typeof import("./app/routes/webhooks.returns.tsx");
  "routes/webhooks.returns.request": typeof import("./app/routes/webhooks.returns.request.tsx");
  "routes/photo.$photoId": typeof import("./app/routes/photo.$photoId.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.tsx");
  "routes/_index": typeof import("./app/routes/_index/route.tsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.tsx");
  "routes/portal": typeof import("./app/routes/portal.tsx");
  "routes/portal.request": typeof import("./app/routes/portal.request.tsx");
  "routes/portal._index": typeof import("./app/routes/portal._index.tsx");
  "routes/track.": typeof import("./app/routes/track..tsx");
  "routes/app": typeof import("./app/routes/app.tsx");
  "routes/app.notifications": typeof import("./app/routes/app.notifications.tsx");
  "routes/app.settings": typeof import("./app/routes/app.settings.tsx");
  "routes/app.returns": typeof import("./app/routes/app.returns.tsx");
  "routes/app.returns.$id": typeof import("./app/routes/app.returns.$id.tsx");
  "routes/app._index": typeof import("./app/routes/app._index.tsx");
  "routes/app.rules": typeof import("./app/routes/app.rules.tsx");
};